server:
  port: 10002

spring:
  application:
    name: edge-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/realms/daily-words
  cloud:
    gateway:
      default-filters:
        - SaveSession
#        - TokenRelay
      routes:
        - id: resource-server-route
          uri: ${RESOURCE_SERVER_URL:http://localhost:10003}
          predicates:
            - Path=/api/v1/words/**